### PR TITLE
ENH: updating testing driver script so it can be run from Windows

### LINKED ISSUE #43: Update testing driver script so it can be run from Windows too
[testing driver](https://github.com/InsightSoftwareConsortium/ITKPerformanceBenchmarking/blob/master/ITK_PerformanceTestingDriver.sh) bash script

### PR DESCRIPTION
**Pull request by dzenanz**
Closes #43.

### CODE REVIEW

**Comment by dzenanz** [comment]
Results of running the script on my computer:
[Testing.tar.gz](https://github.com/InsightSoftwareConsortium/ITKPerformanceBenchmarking/files/1890135/Testing.tar.gz)

**Comment by dzenanz** [comment]
@jhlegarreta "use time format with dots instead of colons" might have been your problem for not having any results. Can you re-try the script now?

**Comment by jhlegarreta** [comment]
@dzenanz thanks for bringing this on the table, and for having worked on this !

I had a look early this morning, and I am willing to give it a try.

I'll try later this week and will let you know.

BTW, I'll upload a new version for [ITKPerformancePlot](https://github.com/jhlegarreta/ITKPerformancePlot) later this week as well. It will hopefully plot the performance as desired.

Will keep you posted.

**Comment by dzenanz** [comment]
Results on my [Linux box](https://github.com/InsightSoftwareConsortium/ITKPerformanceBenchmarking/files/1895158/LinuxBox.tar.gz)

**Comment by hjmjohnson** [comment]
@dzenanz are these linux box results uploaded to girder?

Hans

**Comment by dzenanz** [comment]
No. Where should I upload them?

**Comment by hjmjohnson** [comment]
Please ask @thewtex he had been investigating how to make girder present and hold this material more easily.

**Comment by jhlegarreta** [comment]
@dzenanz **thanks** for making this available to the Windows system and thanks for your patience. The script seems not to provide the expected results in my case, but I am sure **I am missing something**. Any hint could would be appreciated.

This is the output when running it:
```
$ ./ITK_PerformanceTestingDriver.sh
./ITK_PerformanceTestingDriver.sh: line 31: lscpu: command not found
./ITK_PerformanceTestingDriver.sh: line 40: lscpu: command not found
 --
ITK_SRC:
ITK_BLD:
PERF_SRC:
PERF_BLD:
ITK_GIT_TAG:
./ITK_PerformanceTestingDriver.sh: line 100: pushd: no other directory
No local changes to save
Your branch is up-to-date with 'origin/master'.
HEAD is now at 2e7a9a6 Merge pull request #39 from thewtex/update-docker-image
Finished checking out ITK
./ITK_PerformanceTestingDriver.sh: line 105: popd: directory stack empty
./ITK_PerformanceTestingDriver.sh: line 110: pushd: no other directory
Finished compiling config info.
./ITK_PerformanceTestingDriver.sh: line 124: popd: directory stack empty
./ITK_PerformanceTestingDriver.sh: line 129: pushd: no other directory
Building ITK...
Finished bulding ITK
./ITK_PerformanceTestingDriver.sh: line 139: popd: directory stack empty
./ITK_PerformanceTestingDriver.sh: line 144: pushd: no other directory
error: pathspec 'ImproveReportingDiagnostics' did not match any file(s) known to git.
Finished checking out ITKPerformanceBenchmark
./ITK_PerformanceTestingDriver.sh: line 147: popd: directory stack empty
Building and testing perf for  ... \n
{
"ITK_MANUAL_BUILD_INFO": {
 "GIT_CONFIG_DATE": "2018-02-23 09:34:48 -0500",
 "GIT_CONFIG_SHA1": "2e7a9a689513f87ab76de13a74662b4cae7df4ad",
 "GIT_LOCAL_MODIFICATIONS": ""
}
}
\n
mkdir: missing operand
Try 'mkdir --help' for more information.
./ITK_PerformanceTestingDriver.sh: line 150: pushd: no other directory
./ITK_PerformanceTestingDriver.sh: line 154: pushd: no other directory
fatal: Not a valid commit name fca883daf05ac62ee0449513dbd2ad30ff9591f0
./ITK_PerformanceTestingDriver.sh: line 156: popd: directory stack empty
Done with performance testing
./ITK_PerformanceTestingDriver.sh: line 172: popd: directory stack empty
```
If this is a bug, I can open an issue; if it is a local problem, then we can discuss it in a private mail thread to avoid polluting the merge discussion.

**Comment by jhlegarreta** [comment]
@dzenanz True; my own fork was behind master for a few commit, and did not realize when cloning yesterday. Sorry.

Once I realized, and with the current master, unfortunately the json files were not generated. **May be I'm missing something**, but I ran the script with
```
./ITK_PerformanceTestingDriver.sh -s C:/SDKs/ITK/itk-head/ITK -b C:/SDKs/ITK/itk-head-Bin -p C:/Sources/ITKPerformanceBenchmarking -t C:/Binaries/ITKPerformanceBenchmarking -g v4.12.0
```

in my Git bash, and the standard output message was
```
startDir: /c/Sources/ITKPerformanceBenchmarking
ITK_SRC: C:/SDKs/ITK/itk-head/ITK
ITK_BLD: C:/SDKs/ITK/itk-head-Bin
PERF_SRC: C:/Sources/ITKPerformanceBenchmarking
PERF_BLD: C:/Binaries/ITKPerformanceBenchmarking
ITK_GIT_TAG: v4.12.0
/c/SDKs/ITK/itk-head/ITK /c/Sources/ITKPerformanceBenchmarking
No local changes to save
Checking out files: 100% (6888/6888), done.
Note: checking out 'v4.12.0'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b <new-branch-name>

HEAD is now at c513856040... Merge topic 'FixGCC7BuildFailure'
HEAD is now at c513856040 Merge topic 'FixGCC7BuildFailure'
Finished checking out ITK
/c/Sources/ITKPerformanceBenchmarking
/c/SDKs/ITK/itk-head/ITK /c/Sources/ITKPerformanceBenchmarking
Finished compiling config info.
/c/Sources/ITKPerformanceBenchmarking
ITK_SRC: C:/SDKs/ITK/itk-head/ITK
ITK_BLD: C:/SDKs/ITK/itk-head-Bin
mkdir: cannot create directory ‘C:/SDKs/ITK/itk-head-Bin’: File exists
/c/SDKs/ITK/itk-head-Bin /c/Sources/ITKPerformanceBenchmarking
Configuring ITK...
Building ITK...
Finished bulding ITK
/c/Sources/ITKPerformanceBenchmarking
/c/Sources/ITKPerformanceBenchmarking /c/Sources/ITKPerformanceBenchmarking
/c/Sources/ITKPerformanceBenchmarking
Building and testing perf for v4.12.0 ... \n
{
"ITK_MANUAL_BUILD_INFO": {
 "GIT_CONFIG_DATE": "2017-05-31 19:52:37 -0400",
 "GIT_CONFIG_SHA1": "c5138560409c75408ff76bccff938f21e5dcafc6",
 "GIT_LOCAL_MODIFICATIONS": ""
}
}
\n
/c/Binaries/ITKPerformanceBenchmarking /c/Sources/ITKPerformanceBenchmarking
/c/SDKs/ITK/itk-head/ITK /c/Binaries/ITKPerformanceBenchmarking /c/Sources/ITKPerformanceBenchmarking
/c/Binaries/ITKPerformanceBenchmarking /c/Sources/ITKPerformanceBenchmarking
Done with performance testing
/c/Sources/ITKPerformanceBenchmarking
```

**Am I misunderstanding something?** Thanks.

BTW
- Wouldn't be useful to display the usage if the required number of arguments is not provided? If we type the name of the script, the error displayed is unrelated to the arguments and may be misleading in fact.
- Also, does the user need to turn on the ITK testing or examples? I guess they don't but may be we could elaborate on this in the `README.rst`. I'd be happy to help.

**Comment by dzenanz** [comment]
The generated `json` files should be in `C:/Binaries/ITKPerformanceBenchmarking/Examples/Testing/`. The command line which you used should benchmark only one version, the version you specified. The script is essentially expected to be run without any command line arguments, and then it invokes itself with the different git versions in order, starting with `v4.12.0` unless you edit the file and write a different starting version on [line 24](https://github.com/InsightSoftwareConsortium/ITKPerformanceBenchmarking/blob/895bec786fff8aa8abc18e01d3e9fe6167279eef/ITK_PerformanceTestingDriver.sh#L24).

**Comment by jhlegarreta** [comment]
@dzenanz thanks for the additional explanations.

In fact, before running the script with the arguments, I ran it wihout them, and I got:
```
$ ./ITK_PerformanceTestingDriver.sh
startDir: /c/Sources/ITKPerformanceBenchmarking
./ITK_PerformanceTestingDriver.sh: line 23: cd: /c/Sources/ITKPerformanceBenchmarking/ITK: No such file or directory
fatal: ambiguous argument 'v4.12.0..origin/master': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'

```

which led me to think that the script requires a folder named `ITK` to exist in the local source tree, and to have `ITK` cloned into it. Once I had done that, I got:
```
$ ./ITK_PerformanceTestingDriver.sh
startDir: /c/Sources/ITKPerformanceBenchmarking
./ITK_PerformanceTestingDriver.sh: line 28: /c/Sources/ITKPerformanceBenchmarking/ITKPerformanceBenchmarking/ITK_PerformanceTestingDriver.sh: No such file or directory
```

for every hash in the for loop. So modifying [line 27](https://github.com/InsightSoftwareConsortium/ITKPerformanceBenchmarking/blob/895bec786fff8aa8abc18e01d3e9fe6167279eef/ITK_PerformanceTestingDriver.sh#L27) of the script to remove the spare `ITKPerformanceBenchmarking` folder made the script to run, or at least run the `for` loop, but it was unable to do the benchmarking, and I got for every iteration (with the appropriate commit hash):

```
$ ./ITK_PerformanceTestingDriver.sh
startDir: /c/Sources/ITKPerformanceBenchmarking
startDir: /c/Sources/ITKPerformanceBenchmarking
ITK_SRC: /c/Sources/ITKPerformanceBenchmarking/ITK
ITK_BLD: /c/Sources/ITKPerformanceBenchmarking/ITK-bld
PERF_SRC: /c/Sources/ITKPerformanceBenchmarking/ITKPerformanceBenchmarking
PERF_BLD: /c/Sources/ITKPerformanceBenchmarking/ITKPB-bld
ITK_GIT_TAG: ab877c4ebd042ddd1d5e7c44b20084dae416c284
/c/Sources/ITKPerformanceBenchmarking/ITK /c/Sources/ITKPerformanceBenchmarking
No local changes to save
Previous HEAD position was c513856040... Merge topic 'FixGCC7BuildFailure'
HEAD is now at ab877c4ebd... Merge branch 'pygccxml-upstream' into pygccxml-update
HEAD is now at ab877c4ebd Merge branch 'pygccxml-upstream' into pygccxml-update
Finished checking out ITK
/c/Sources/ITKPerformanceBenchmarking
/c/Sources/ITKPerformanceBenchmarking/ITK /c/Sources/ITKPerformanceBenchmarking
Finished compiling config info.
/c/Sources/ITKPerformanceBenchmarking
ITK_SRC: /c/Sources/ITKPerformanceBenchmarking/ITK
ITK_BLD: /c/Sources/ITKPerformanceBenchmarking/ITK-bld
/c/Sources/ITKPerformanceBenchmarking/ITK-bld /c/Sources/ITKPerformanceBenchmarking
Configuring ITK...
Building ITK...
Finished bulding ITK
/c/Sources/ITKPerformanceBenchmarking
/c/Sources/ITKPerformanceBenchmarking/ITK_PerformanceTestingDriver.sh: line 129: pushd: /c/Sources/ITKPerformanceBenchmarking/ITKPerformanceBenchmarking: No such file or directory
/c/Sources/ITKPerformanceBenchmarking/ITK_PerformanceTestingDriver.sh: line 132: popd: directory stack empty
Building and testing perf for ab877c4ebd042ddd1d5e7c44b20084dae416c284 ... \n
{
"ITK_MANUAL_BUILD_INFO": {
 "GIT_CONFIG_DATE": "2017-05-29 14:14:57 -0400",
 "GIT_CONFIG_SHA1": "ab877c4ebd042ddd1d5e7c44b20084dae416c284",
 "GIT_LOCAL_MODIFICATIONS": ""
}
}
\n
/c/Sources/ITKPerformanceBenchmarking/ITKPB-bld /c/Sources/ITKPerformanceBenchmarking
/c/Sources/ITKPerformanceBenchmarking/ITK /c/Sources/ITKPerformanceBenchmarking/ITKPB-bld /c/Sources/ITKPerformanceBenchmarking
/c/Sources/ITKPerformanceBenchmarking/ITKPB-bld /c/Sources/ITKPerformanceBenchmarking
Done with performance testing
```

So there seems to be another issue, may be on **line 129**.

**May be I'm missing something**.

**Comment by dzenanz** [comment]
Yes, ITK source folder needs to exist. The script should be called from one
folder up. Writing from cellphone.

**Comment by jhlegarreta** [comment]
@dzenanz thanks for the support.

I tried with no argument and got
```
$ ./ITKPerformanceBenchmarking/ITK_PerformanceTestingDriver.sh
startDir: /c/Sources
fatal: Not a git repository (or any of the parent directories): .git
```

Looks like the root needs to be a git repo as well. Once I did a `git init`, with an empty ITK folder, I got
```
$ ./ITKPerformanceBenchmarking/ITK_PerformanceTestingDriver.sh
startDir: /c/Sources/Performance
fatal: ambiguous argument 'v4.12.0..origin/master': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
```
So I finally cloned ITK into the folder at issue, and then the script looked to start working, or looping over the commit hashes, but I got no JSON in the folder you mentioned.

However, ITK is not actually being built, since in the `ITK-bld` folder no lib is created, so that's may be the reason why there is no trace about the JSONs.

The *CMake* and *Ninja* tools are not found according to the log files in ITK-bld. Shouldn't the script stop and inform the user in that case?

I think users would welcome if this was explained in the *README* or the prompt.

I'll try to find the way to tell the Git bash where CMake is and installing Ninja.

**Comment by dzenanz** [comment]
CMake needs to be in the path, or else it will not be found. When installing CMake, you have the option to add it to the path.

Ninja needs to be in the path too. And for Ninja to find MSVC (instead of GCC from Anaconda or git or somewhere) cl.exe needs to be in the path too. That's what the other [script](https://github.com/InsightSoftwareConsortium/ITKPerformanceBenchmarking/blob/master/RunWithVisualStudio.cmd) is for.

**Comment by jhlegarreta** [comment]
Thanks for the support @dzenanz and sorry for the delay: it took me a while, but already added cmake, ninja and cl to the toolchain, and run the script. Unfortunately, no JSON was generated :sob: .

I ignore whether the message for the `mkdir` command is just a notice/warning about the non-empty `ITK-bld` folder or else, whether that is an error and the folder should not exist:
```
mkdir: cannot create directory ‘/c/Sources/ITK-bld’: File exists
```

In either case, the first pass did not generate any JSON file, so I am not able to reproduce the results :confused:.

To be honest, I do not think that `ITK` is being actually built; the folder `ITK-bld` does not contain any library or MSVC-related files. All **cmake**, **ninja** and **cl** are on my path, and have checked that the `--version` option and `cl` itself show their corresponding versions, so I do not see where I should be missing something.

**Comment by dzenanz** [comment]
What happens if you execute the commands manually from Git Bash?
```bash
cd ITK-bld
cmake -G Ninja \
      -DCMAKE_BUILD_TYPE:STRING=Release \
      -DCMAKE_CXX_STANDARD:STRING=11 \
      -DBUILD_TESTING:BOOL=OFF \
      -DBUILD_EXAMPLES:BOOL=OFF \
      ../ITK
ninja
```

**Comment by jhlegarreta** [comment]
@dzenanz Thanks for the relentless effort to uncover any issue.

The CMake config process fails with the following error
```
$ cmake -G Ninja \
>       -DCMAKE_BUILD_TYPE:STRING=Release \
>       -DCMAKE_CXX_STANDARD:STRING=11 \
>       -DBUILD_TESTING:BOOL=OFF \
>       -DBUILD_EXAMPLES:BOOL=OFF \
>       ../ITK
CMake Error at C:/Program Files/CMake/share/cmake-3.10/Modules/CMakeDetermineCompilerId.cmake:145 (file):
  file problem creating directory:
  C:/Sources/ITK-bld/CMakeFiles/3.10.2/CompilerIdCXX
Call Stack (most recent call first):
  C:/Program Files/CMake/share/cmake-3.10/Modules/CMakeDetermineCompilerId.cmake:31 (CMAKE_DETERMINE_COMPILER_ID_BUILD)
  C:/Program Files/CMake/share/cmake-3.10/Modules/CMakeDetermineCXXCompiler.cmake:107 (CMAKE_DETERMINE_COMPILER_ID)
  CMakeLists.txt:32 (project)


-- The CXX compiler identification is MSVC 19.0.24215.1
-- The C compiler identification is MSVC 19.0.24215.1
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/cl.exe
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/cl.exe -- broken
CMake Error at C:/Program Files/CMake/share/cmake-3.10/Modules/CMakeTestCXXCompiler.cmake:45 (message):
  The C++ compiler

    "C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/cl.exe"

  is not able to compile a simple test program.

  It fails with the following output:

    Change Dir: C:/Sources/ITK-bld/CMakeFiles/CMakeTmp

    Run Build Command:"C:/PROGRA~1/Ninja/ninja.exe" "cmTC_4b853"
    [1/2] Building CXX object CMakeFiles\cmTC_4b853.dir\testCXXCompiler.cxx.obj
    [2/2] Linking CXX executable cmTC_4b853.exe
    FAILED: cmTC_4b853.exe
    cmd.exe /C "cd . && "C:\Program Files\CMake\bin\cmake.exe" -E vs_link_exe --intdir=CMakeFiles\cmTC_4b853.dir --manifests  -- C:\PROGRA~2\MICROS~3.0\VC\bin\link.exe /nologo CMakeFiles\cmTC_4b853.dir\testCXXCompiler.cxx.obj  /out:cmTC_4b853.exe /implib:cmTC_4b853.lib /pdb:cmTC_4b853.pdb /version:0.0  /machine:X86  /debug /INCREMENTAL /subsystem:console  kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib && cd ."
    RC Pass 1: command "rc /foCMakeFiles\cmTC_4b853.dir/manifest.res CMakeFiles\cmTC_4b853.dir/manifest.rc" failed (exit code 0) with the following output:
    The system cannot find the file specified
    ninja: build stopped: subcommand failed.




  CMake will not be able to correctly generate this project.
Call Stack (most recent call first):
  CMakeLists.txt:32 (project)


-- Configuring incomplete, errors occurred!
See also "C:/Sources/ITK-bld/CMakeFiles/CMakeOutput.log".
See also "C:/Sources/ITK-bld/CMakeFiles/CMakeError.log".
````

The `CMakeError.log` contains the above content, plus (at an earlier stage in the CMake config process)
```
/out:CMakeCCompilerId.exe 
CMakeCCompilerId.obj 
LINK : fatal error LNK1104: cannot open file 'LIBCMT.lib'
```

for the times when I tried to run the `ITKPerformanceBenchmarking.sh`. So I'd need to investigate about it.

Although a hypothesis may be that all of this stems from the top problem outlined:
```
file problem creating directory:
```
that is weird, since the pointed directory (`C:/Sources/ITK-bld/CMakeFiles/3.10.2/CompilerIdCXX`) exists indeed, and it cannot be a rights problem, since at least some directories are actually being created.

:worried:

**Comment by dzenanz** [comment]
> The C++ compiler
>   "C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/cl.exe"
>  is not able to compile a simple test program.

This happened to me when I just added _C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/_ to `PATH`. I needed to run [vcvars.bat](https://github.com/InsightSoftwareConsortium/ITKPerformanceBenchmarking/blob/master/RunWithVisualStudio.cmd#L1). You might want to update `RunWithVisualStudio.cmd` to point to your appropriate vcvars (e.g. _C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\bin\amd64\vcvars64.bat_) and start the GitBash by double-clicking on `RunWithVisualStudio.cmd` in Explorer. Then add _CMake_ and _ninja_ to your `PATH` if they are not already in it.

**Comment by jhlegarreta** [comment]
@dzenanz **sorry**, I've been lagging behind this as well.

Although I had to **change the path** to the batch file to `{PATH_TO_MSVC}\VC\vcvarsall.bat`, **that worked, at least partially**. **Thanks** for the tip !

Unfortunately, the performance benchmarking JSON's are still elusive; ITK libraries seem to have been built, but not sure whether correctly, since I got **some file corrupted and linking error thereof** at some stage:

```
(...)

CMake Warning (dev) at ITK-bld/ITKTargets.cmake:96 (add_library):
  ADD_LIBRARY called with SHARED option but the target platform does not
  support dynamic linking.  Building a STATIC library instead.  This may lead
  to problems.
Call Stack (most recent call first):
  ITK-bld/ITKConfig.cmake:54 (include)
  CMakeLists.txt:7 (find_package)
This warning is for project developers.  Use -Wno-dev to suppress it.

(...)
-- Build files have been written to: C:/Sources/ITKPerformanceBenchmarking/ITKPB-bld
[1/57] Creating directories for 'KWStyle'

(...)
[9/57] Linking CXX shared library ..\ITK-bld\bin\itkPerformanceBenchmarking-4.12.dll
FAILED: ../ITK-bld/bin/itkPerformanceBenchmarking-4.12.dll ../ITK-bld/lib/itkPerformanceBenchmarking-4.12.lib

LINK: command "C:\PROGRA~2\MICROS~3.0\VC\bin\link.exe /nologo src\CMakeFiles\PerformanceBenchmarking.dir\jsonxx.cc.obj src\CMakeFiles\PerformanceBenchmarking.dir\__\PerformanceBenchmarkingInformation.cxx.obj src\CMakeFiles\PerformanceBenchmarking.dir\itkHighPriorityRealTimeClock.cxx.obj src\CMakeFiles\PerformanceBenchmarking.dir\itkHighPriorityRealTimeProbe.cxx.obj src\CMakeFiles\PerformanceBenchmarking.dir\itkHighPriorityRealTimeProbesCollector.cxx.obj src\CMakeFiles\PerformanceBenchmarking.dir\PerformanceBenchmarkingUtilities.cxx.obj /out:..\ITK-bld\bin\itkPerformanceBenchmarking-4.12.dll /implib:..\ITK-bld\lib\itkPerformanceBenchmarking-4.12.lib /pdb:..\ITK-bld\bin\itkPerformanceBenchmarking-4.12.pdb /dll /version:1.0 /machine:X86 /INCREMENTAL:NO ..\ITK-bld\bin\ITKCommon-4.12.dll ..\ITK-bld\lib\itksys-4.12.lib ws2_32.lib Psapi.lib ..\ITK-bld\lib\ITKVNLInstantiation-4.12.lib ..\ITK-bld\lib\itkvnl_algo-4.12.lib ..\ITK-bld\lib\itkvnl-4.12.lib ..\ITK-bld\lib\itkv3p_netlib-4.12.lib ..\ITK-bld\lib\itknetlib-4.12.lib ..\ITK-bld\lib\itkvcl-4.12.lib kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib /MANIFEST /MANIFESTFILE:..\ITK-bld\bin\itkPerformanceBenchmarking-4.12.dll.manifest" failed (exit code 1107) with the following output:
..\ITK-bld\bin\ITKCommon-4.12.dll : fatal error LNK1107: invalid or corrupt file: cannot read at 0x318

```

DLLs have been created at `\ITK-bld\bin\` and LIBs at `\ITK-bld\lib\`. 

Unless the value for the ITK flag `BUILD_SHARED_LIBS` is incorrect, I cannot think of any other reason why this should fail if it is working elsewhere 😕

**Comment by thewtex** [comment]
```
CMake Warning (dev) at ITK-bld/ITKTargets.cmake:96 (add_library):
  ADD_LIBRARY called with SHARED option but the target platform does not
  support dynamic linking.  Building a STATIC library instead.  This may lead
  to problems.
```

This is a strange error. Are you using TBB?

Maybe we should turn `BUILD_SHARED_LIBS` `OFF` to make it easier on Windows (no RPATH).

**Comment by jhlegarreta** [comment]
@thewtex no, I was not using TBB.

But, the good news is that thanks to the `BUILD_SHARED_LIBS` `OFF` change in #51, the benchmarks were built 🎆 :

```
Test project C:/Sources/ITKPerformanceBenchmarking/ITKPB-bld
      Start  1: PerformanceBenchmarkingKWStyleTest
 1/20 Test  #1: PerformanceBenchmarkingKWStyleTest ...........   Passed    0.31 sec
      Start  2: PerformanceBenchmarkingInDoxygenGroup
 2/20 Test  #2: PerformanceBenchmarkingInDoxygenGroup ........   Passed    0.42 sec

 (...)

100% tests passed, 0 tests failed out of 20

Label Time Summary:
Core                       =   0.67 sec*proc (1 test)
Filtering                  =  36.01 sec*proc (5 tests)
PerformanceBenchmarking    =   7.29 sec*proc (6 tests)
Registration               =  44.52 sec*proc (3 tests)
Segmentation               =  85.17 sec*proc (4 tests)

Total Test time (real) = 179.38 sec

ITK Repository Information:
{'ITK_MANUAL_BUILD_INFORMATION': {'GIT_CONFIG_SHA1': 'c5138560409c75408ff76bccff938f21e5dcafc6', 'GIT_LOCAL_MODIFICATIONS': '', 'GIT_CONFIG_DATE': '2017-05-31 19:52:37 -0400'}}

Building ITK...
Building benchmarks...
Running benchmarks...
Done running performance benchmarks.
```

So the JSON files now in `ITKPerformanceBenchmarking\ITKPB-bld\BenchmarkResults\{MY_MACHINHE_NAME}`. This is awesome, **Thanks both** for your support.

I'll make a note in the [README.rst](https://github.com/InsightSoftwareConsortium/ITKPerformanceBenchmarking/blob/master/README.rst) file to add additional notes that may be helpful to reproduce the results in Windows.

**Pull request merged**
