### PR TITLE
ENH: Add benchmark which estimates the overhead of additional thread

### PR DESCRIPTION
**Pull request by blowekamp**

### CODE REVIEW

**Comment by blowekamp** [comment]
I am sorry I don't understand what you want for output.

The point of this benchmark is to compute how long it takes to "spawn" a thread. This is different than the other tests. Additionally, there is no difference in formatting from using the individual probs than a collector:
```
Name Of Probe (Time)          Iterations     Total (s)      Min (s)        Mean (s)       Max (s)        StdDev (s)     
FilterWithThreads-1           1000           0.00103927     9.53674e-07    1.03927e-06    1.19209e-05    4.18912e-07    
FilterWithThreads-100         1000           2.18768        0.00160003     0.00218768     0.00323796     0.000408993    
Estimated overhead cost per thread: 16.1523 micro-seconds
```

Regarding the use of the RealTime vs the standard clock, it's unclear to me how the priority affects the overhead of thread spawning. Spawning threads clearly involves significant OS work. So I am unsure if making the process "real-time" provides realistic times or not. It is currently a commented out typedef.

**Comment by thewtex** [comment]
The `HighPriorityRealTimeProbe` and `HighPriorityRealTimeProbesCollector` are drop-in replacements for the non-HighPriority counterparts, and they generally reduce the variability of measurements. For more information, please see the Insight Journal article.

**Comment by blowekamp** [comment]
Any open issues with this pull request?

**Comment by thewtex** [comment]
This fails to build:

   https://circleci.com/gh/InsightSoftwareConsortium/ITKPerformanceBenchmarking/76


CircleCI had disabled PR builds -- these have been re-enabled.

**Comment by blowekamp** [comment]
What version of ITK is it build with?
This patch updated the ITK version to include the following patch:
http://review.source.kitware.com/#/c/22477/

**Comment by thewtex** [comment]
The ITK version was from 2016.  I will create a PR to update it to master from today.

**Pull request merged**
