### PR TITLE
DOC: Point self `README` links to `master` versions

### PR DESCRIPTION
**Pull request by jhlegarreta**
Point self `README` links to `master` versions.

### CODE REVIEW

**Comment by jhlegarreta** [comment]
The previous version would always be correct (unless the git history is re-written), even if such files are modified and those statements no longer exist in the `master` branch. The current solution might point to inaccurate lines if the latter happens, but that  would be the contributor's task, or would be fixed at a latter iteration.

**Review by thewtex — APPROVED** [review]
:+1:

**Comment by jhlegarreta** [comment]
Will follow with a patch set during the weekend, as I now see that the `master` link does not point to the appropriate line in the Python script: it should point to
https://github.com/InsightSoftwareConsortium/ITKPerformanceBenchmarking/blob/master/evaluate-itk-performance.py#L139

**Comment by jhlegarreta** [comment]
Re https://github.com/InsightSoftwareConsortium/ITKPerformanceBenchmarking/pull/94#issuecomment-2136319668 Done in PR #99.

**Pull request merged**
